### ISSUE TITLE
Pip widget issue

### ISSUE THREAD

**Issue by ragul-pr** [harshitverma209/android_pip#2] opened 2024-07-17 04:29 UTC
Yeah now that's working fine. But still, the pip widget doesn't make returns the pip child instead it returns same widget in pip. Can you please check and the simple pip works fine on this case. this plugin doesn't work as expected.

**Comment by harshitverma209** [comment] 2024-08-12 11:37
Hey, can you please provide a minimal reproducible sample?

**Comment by harshitverma209** [comment] 2024-09-30 15:05
Closing this as a duplicate of #1

**Closed as completed** 2024-09-30 15:05 UTC
